### ISSUE TITLE
EMC breaking

### ISSUE THREAD

**Issue by paxtone91** [DatSquirrel7/Modpack-DRM#1]
with the low emc value of quartz slivers and the return on making them into vis crystals you can use any item with high levels of attribute such as the thaumonomicon to rapidly increase your emc at a crucible with an everflowing urn. the only draw back is that it will inevitably create a rift. but it is thousands of profit easily.

**Comment by DatSquirrel7** [comment]
Values for Vis Crystals Adjusted.
