### ISSUE TITLE
Missing materials

### ISSUE THREAD

**Issue by paxtone91** [DatSquirrel7/Modpack-DRM#2]
Refined obsidian, refined glowstone, mana steel, terrasteel, Elementium, Gaia spirit, yellorium, cyanite, blutonium, Ludicrite, quartz enriches iron, draconium(all variants), psimetal(all varients), psigem, fluxed electrum, refined iron, tungsten, titanium, chrome, advanced alloy, rubber, certus quartz, fluix crystal. Have fun

**Comment by DatSquirrel7** [comment]
Refined Obsidian, Refined Glowstone, Yellorium, Cyanite, Blutonium, Ludicrite, QEI, Psimetal, Psigem, Fluxed, Electrum, Refined Iron, Tungsten, Titanium, Chrome, Advanced Alloy, Rubber, Certus Quartz, and Fluix materials removed. 

Others will be added as of 1.10.
